### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by torneq** [Jakkoble/TwitchWhitelist#1]
Hi.

After installation, plugin is working fine. When im trying to get into server after being added to whitelist it works but I can join either from another account without using Twitch points.
And yes, i have my vanilla whitelist off.

Thanks in advance for solving this.

**Comment by Jakkoble** [comment]
Hey!

Sorry for the late response. I was very busy.
I guess you tried to use the Plugin on a old Version Server like 1.8 or something like that. The Plugin is used to work in the newer Versions of Minecraft like 1.19. I will add functionality for 1.8-1.19 as soon as possible and notify you in this issue on release. 

Thank you for your time!

**Comment by Jakkoble** [comment]
Hey there!

The Plugin works now on 1.8 - 1.19 Spigot and PaperMC Servers. 
I hope your troubles are fixed now and sorry again for the late Response.

Dears Jakob
