### ISSUE TITLE
Feature Request: allow customizable command

### ISSUE THREAD

**Issue by Swirren** [Jakkoble/TwitchWhitelist#4]
I'd love to use this plugin but my server is public. I'd rather allow channel points to be used to run some other command. Optimally there's the option for many commands to be run from a list

**Comment by Jakkoble** [comment]
Hey, thank you for your issue!

Could you give me an more specific example? Did I understood you right, you want to disable the Whitelist, have some sort of list in the config where you can but commands in it and if a Channel Points Reward is triggerd a random command gets executed?

**Comment by Swirren** [comment]
I'm talking about basically revamping the use of this plugin. Instead of just one command/feature (the whitelist) you instead open it up to anything the player wants to run when the channel point reward is redeemed. As for random, that wasn't the original intent,but a separate section for commands in a list to be chosen at random would be nice too

**Comment by Jakkoble** [comment]
Oh okay, now I understand you. 

I already planned the integration of Mutliple Features with different Channel Point Rewards. But this process is very complex and will take some time. Until when do you need the Plugin Version with a Command integration? So for the full version with many features I need to restructure the whole project and this needs some time. I could create you a temporarily custom version of the plugin for you if it rushes. For this you must exactly list what features you absolutely need.

I really thank you for your suggention and feedback!

**Comment by Swirren** [comment]
I'm good, this would be a bonus plugin for me. I don't mind waiting for awesome features!

**Comment by Jakkoble** [comment]
That sounds great!

I will try my best to restructure my project as soon as possible.

Thank you for your flexibility!
