### ISSUE TITLE
TwitchWhitelist

### ISSUE THREAD

**Issue by jefflima1** [Jakkoble/TwitchWhitelist#5]
Is it possible to remove the difference between uppercase and lowercase in the nicknames to be placed in the withelist?

**Comment by Jakkoble** [comment]
Hey there! Thank you for your request. Are you talking about the name you type inside a Custom Channel Reward on Twitch? And are you using the plugin on an Offline Server?

**Comment by Jakkoble** [comment]
I reworked some parts of the code now. Now the Player Names are non case sensitive. E.g. My MC Name is 'Jakkoble', now I can add 'JaKkOBlE' and this works just fine. (also for removing)
Hopefully this fixes the issue you mentioned. Now I will do some tests and notify you when I publish the new plugin version.

**Comment by Jakkoble** [comment]
Hey there again!

Here is the new version of the plugin: **[Link](https://github.com/Jakkoble/TwitchWhitelist/releases/latest)**
I hope this fixed your problem. Feel free to answer on this issue if so.

**Comment by jeffl1ma** [comment]
Our friend congratulations, I simply opened the call, went to sleep and woke up the problem was solved, you are incredible, everything worked, thank you very much!

**Comment by Jakkoble** [comment]
No problem, glad to hear you're satisfied. 
If you have some time left I would really appreciate a small review on my **[Spigot MC Page](https://www.spigotmc.org/resources/twitchwhitelist-whitelist-players-via-twitch-channelpoints.105744)** (simply by giving a star rating on the right side) and give this repository a ⭐ on GitHub.
Thank you in advance!
